from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('button', src, depend = ['BUTTON_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
