from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('button', src, depend = ['PKG_USING_BUTTON'], CPPPATH = CPPPATH)

Return('group')
